### ISSUE TITLE
大佬我什么第一个py文件运行不了

### ISSUE THREAD

**Issue by fgzdffg** [Mr-Deng67/Genshin-QR#1]

**Comment by fgzdffg** [comment]
文件需要二次编辑吗

**Comment by Mr-Deng67** [comment]
导入的包都装好了吗

**Comment by fgzdffg** [comment]
文件需要添加Cookie这吗

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年10月1日 19:15
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Mr-Deng67/Genshin-QR] 大佬我什么第一个py文件运行不了 (Issue #1)


导入的包都装好了吗

―

**Comment by Mr-Deng67** [comment]
要，你先把程序运行起来再说

**Comment by fgzdffg** [comment]
运行第一个吗

**Comment by Mr-Deng67** [comment]
> 运行第一个吗

对

**Comment by fgzdffg** [comment]
我用Python为什么闪退

**Comment by fgzdffg** [comment]
框架可以运行

**Comment by Mr-Deng67** [comment]
> 我用Python为什么闪退

你是用什么方式运行的，截个图看下

**Comment by fgzdffg** [comment]
大佬可以加v聊吗 v:_19356613893

**Comment by fgzdffg** [comment]
要转EXE吗

**Comment by fgzdffg** [comment]
我直接用Python运行的
